name: telebirr
services:
  - name: api
    type: web
    port: 8000
    build:
      type: docker
      dockerfile: Dockerfile
    env:
      - key: DATABASE_URL
        value: postgresql://postgres:1dBufXeykxdVBsrJ@mctmbhyqosnmbqorlhna.db.eu-central-1.nhost.run:5432/mctmbhyqosnmbqorlhna
      - key: SECRET_KEY
        value: changeme
      - key: ENVIRONMENT
        value: production
      - key: NHOST_DB_HOST
        value: mctmbhyqosnmbqorlhna.db.eu-central-1.nhost.run
      - key: NHOST_DB_PORT
        value: "5432"
      - key: NHOST_DB_USER
        value: postgres
      - key: NHOST_DB_PASSWORD
        value: 1dBufXeykxdVBsrJ
      - key: NHOST_DB_NAME
        value: mctmbhyqosnmbqorlhna
      - key: NHOST_JWT_SECRET
        value: changeme
      - key: NHOST_WEBHOOK_SECRET
        value: changeme
    health_check:
      http:
        path: /
        port: 8000
        interval: 30s
        timeout: 10s
        retries: 3
    instance_type: small
    regions:
      - eu-central-1
